report : report.tex Julia.jpeg test0.bmp test3.bmp test7.bmp test8.bmp test9.bmp julia.pdf
	xelatex report
	rm report.log report.aux report.bbl report.blg

slide : slide.tex Julia.jpeg test0.bmp test3.bmp test7.bmp test8.bmp test9.bmp julia.pdf
	xelatex slide
	rm slide.log slide.aux slide.nav slide.snm slide.out slide.toc
